#include <iostream.h>
#include <conio.h>
#include <time.h>
main()
{
	cout << "\x1b\x0c";

	cout << "\x1b\x4d\x1b\x43Pro-Data \x1b\x45\x1b\x4c\x1b\x5c";
	time_t t;
	time(&t);
	cout << ctime(&t);
	cout << "\x1b\x0a\x1b\x0a";
	cout << "\x1b\x44\x1b\x5d\x1b\x43Welcome to Steve's Retro Loft";
	cout << "\x1b\x0a\x1b\x0a";
	//cout  "1234567890123456789012345678901234567890";
	//cout << "\x1b\x0a";
	cout << "Welcome to the Retro Loft's Viewdata";
	cout << "\x1b\x0a";
	cout << "service, it's been a long time in the";
	cout << "\x1b\x0a";
	cout << "making. Although I did have a 20 or so";
	cout << "\x1b\x0a";
	cout << "year gap.  Still good things come to";
	cout << "\x1b\x0a";
	cout << "those that wait.";
	cout << "\x1b\x0a";
	cout << "";
	cout << "\x1b\x0a";
	cout << "Anyway - Random text now just to fill up";
	cout << "\x1b\x0a";
	cout << "the space and screen buffer.";
	cout << "\x1b\x0a";
	cout << "";
	cout << "\x1b\x0a";
	cout << "";
	cout << "\x1b\x0a";
	cout << "";
	cout << "\x1b\x0a";
	cout << "\x1b\x0a";
	cout << "\x1b\x0a";
	cout << "";
	cout << "\x1b\x0a";
	cout << "";
	cout << "\x1b\x0a";
	cout << "";


	cout << "\x1b\x44\x1b\x5d\x1b\x43 (c) Stephen Cooper 1996/2021";
	return 0;
}